// Generated by LiveScript 1.3.1
ld$.fetch('gradients.json', {}, {
  type: 'json'
}).then(function(colors){
  colors.sort(function(a, b){
    return ldColor.hcl(a.colors[0]).h - ldColor.hcl(b.colors[0]).h;
  });
  return colors.filter(function(it){
    return it.colors.length;
  }).map(function(it){
    var node;
    node = document.createElement("div");
    container.appendChild(node);
    return new GradientEditor({
      root: node,
      colors: it.colors,
      dir: it.dir
    });
  });
});