// Generated by LiveScript 1.3.1
var colors;
colors = [['#f0f', '#0ff'], ['#ff0', '#f0f'], ['#ff9', '#fc9'], ['#5f9', '#7ff'], ['#f00', '#f93'], ['#fbd786', '#f7797d']];
colors.map(function(it){
  var node;
  node = document.createElement("div");
  document.body.appendChild(node);
  return new GradientEditor({
    root: node,
    colors: it
  });
});