// Generated by LiveScript 1.3.1
var fs, gradients;
fs = require('fs');
gradients = fs.readFileSync('gradient-180.txt').toString().split('\n').map(function(it){
  var dir, colors;
  it = it.split(',');
  dir = +it.splice(0, 1)[0];
  colors = it.map(function(it){
    it = it.trim().split(' ');
    return {
      hex: it[0],
      offset: +it[1] / 100
    };
  });
  colors.sort(function(a, b){
    return a.offset - b.offset;
  });
  return {
    dir: dir,
    colors: colors
  };
});
fs.writeFileSync('gradients.json', JSON.stringify(gradients));